import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Sparkles, Check, Image as ImageIcon, Monitor, Smartphone, Share2, HelpCircle, ExternalLink, Download } from "lucide-react";
import IndianFlag from "@/components/IndianFlag";
import { TEMPLATES } from "@/data/templates";

// Filter only available templates
const AVAILABLE_TEMPLATES = TEMPLATES.filter((t) => t.isAvailable);

export const metadata: Metadata = {
  title: "Independence Day 2026 Wallpaper | HD 15 August Wallpapers",
  description: "Explore HD Independence Day 2026 wallpapers for mobile, desktop and social media. Find patriotic Indian flag wallpapers and create a personalized 15 August poster with your own photo.",
  alternates: { canonical: "https://freedom2026.in/independence-day-wallpaper" },
  openGraph: {
    title: "Independence Day 2026 Wallpaper | HD 15 August Wallpapers",
    description: "Explore HD Independence Day 2026 wallpapers for mobile, desktop and social media. Find patriotic Indian flag wallpapers and create a personalized 15 August poster with your own photo.",
    url: "https://freedom2026.in/independence-day-wallpaper",
    type: "website",
    images: [
      {
        url: "https://freedom2026.in/images/hero_poster_main.png",
        width: 1080,
        height: 1350,
        alt: "Independence Day 2026 Wallpaper",
      },
    ],
  },
};

const MOBILE_WALLPAPERS = [
  { src: "/images/hero_poster_main.png", alt: "15 August 2026 patriotic mobile wallpaper" },
  { src: "/images/hero_poster_left.png", alt: "Happy Independence Day 2026 wallpaper for phone" },
  { src: "/images/hero_poster_right.png", alt: "15 August freedom mobile wallpaper" },
  { src: "/images/portrait-style.png", alt: "Indian tricolor mobile wallpaper" },
];

const DESKTOP_WALLPAPERS = [
  { src: "/images/video_mockup.png", alt: "Independence Day desktop wallpaper India" },
  { src: "/images/classic-india-style.png", alt: "15 August 2026 desktop background" },
];

const FLAG_WALLPAPERS = [
  { src: "/images/india-map-style.png", alt: "Independence Day 2026 Indian flag wallpaper" },
  { src: "/images/modern-india-style.png", alt: "Indian tricolor Independence Day wallpaper" },
];

export default function IndependenceDayWallpaperPage() {
  const faqs = [
    {
      q: "What is an Independence Day 2026 wallpaper?",
      a: "It is a high-definition digital image featuring patriotic themes, the Indian tricolor, or freedom fighters, designed to be used as a background on mobile phones, tablets, or desktop computers to celebrate India's Independence Day on 15 August 2026."
    },
    {
      q: "Where can I use a 15 August wallpaper?",
      a: "You can set them as your mobile lock screen, home screen, desktop background, or even use them as WhatsApp status updates and Instagram stories."
    },
    {
      q: "Can I use these wallpapers on my phone?",
      a: "Yes, our mobile wallpapers are vertically oriented and optimized to fit perfectly on smartphone screens without losing quality or cropping important patriotic elements."
    },
    {
      q: "Are there desktop Independence Day wallpapers?",
      a: "Yes, we provide wallpapers that look stunning on larger, horizontal displays, giving your computer a patriotic look for the 15th of August."
    },
    {
      q: "Can I use an Indian flag wallpaper?",
      a: "Absolutely. We have a dedicated collection of Indian flag wallpapers celebrating the beauty of the tricolor, available for you to view and use."
    },
    {
      q: "Can I create an Independence Day poster with my own photo?",
      a: "Yes, in addition to standard wallpapers, we offer a tool where you can upload your photo, select a premium patriotic style, and generate a customized poster."
    },
    {
      q: "How much does a personalized poster cost?",
      a: "Creating a personalized HD poster starts at ₹49. Some of our exclusive premium templates may have different pricing."
    },
    {
      q: "Can I download my personalized HD poster?",
      a: "Yes, once your personalized poster is generated by our AI after checkout, you can download it directly in high definition."
    }
  ];

  const socialUses = [
    { name: "Mobile Lock Screen", icon: Smartphone },
    { name: "Mobile Home Screen", icon: Smartphone },
    { name: "Desktop Background", icon: Monitor },
    { name: "WhatsApp Status", icon: Share2 },
    { name: "Instagram Stories", icon: ImageIcon },
    { name: "Facebook Posts", icon: Share2 },
    { name: "Profile Pictures", icon: ImageIcon }
  ];

  const targetAudiences = [
    "Students",
    "Professionals",
    "Families",
    "Teachers",
    "Businesses",
    "Creators",
    "Patriotic Citizens",
    "Schools & Communities"
  ];

  // Schema generation
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map(faq => ({
      "@type": "Question",
      "name": faq.q,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.a
      }
    }))
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://freedom2026.in/"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "Independence Day Wallpaper",
        "item": "https://freedom2026.in/independence-day-wallpaper"
      }
    ]
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      {/* ══ HEADER / HERO SECTION ══ */}
      <section className="relative pt-24 pb-16 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-orange-50 via-white to-emerald-50 z-0" />
        <div className="absolute inset-0 bg-[url('/patterns/topography.svg')] opacity-5 z-0" />
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center max-w-4xl mx-auto space-y-4 sm:space-y-6">
            <div className="inline-flex items-center gap-1.5 sm:gap-2 bg-white border border-slate-200 text-slate-700 text-[10px] sm:text-xs font-bold px-3 sm:px-4 py-1 sm:py-1.5 rounded-full shadow-sm">
              <Monitor className="w-3.5 h-2.5 sm:w-4 sm:h-3" />
              <span>Mobile & Desktop Collection</span>
            </div>
            
            <h1 className="text-3xl sm:text-5xl md:text-6xl font-black text-[#0f172a] tracking-tight leading-tight px-2">
              Independence Day 2026 Wallpaper
            </h1>
            
            <h2 className="text-lg sm:text-2xl font-bold text-slate-700 px-4">
              HD 15 August Wallpapers for Mobile & Desktop
            </h2>
            
            <p className="text-sm sm:text-lg text-slate-600 max-w-2xl mx-auto leading-relaxed px-2">
              Celebrate India's Independence Day with HD patriotic wallpapers featuring the Indian flag, tricolor themes and the spirit of 15 August.
            </p>
            
            <div className="pt-2 sm:pt-4 flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-4 px-4">
              <Link
                href="/create"
                className="w-full sm:w-auto px-6 sm:px-8 py-3.5 sm:py-4 bg-gradient-to-r from-[#f97316] to-[#ea580c] text-white rounded-xl sm:rounded-2xl font-black text-base sm:text-lg shadow-lg shadow-orange-500/25 hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4 sm:w-5 sm:h-5" />
                Create Your Personalized Poster
              </Link>
              <Link
                href="#wallpapers"
                className="w-full sm:w-auto px-6 sm:px-8 py-3.5 sm:py-4 bg-white text-slate-700 rounded-xl sm:rounded-2xl font-bold text-base sm:text-lg border-2 border-slate-200 hover:border-slate-300 hover:bg-slate-50 transition-all flex items-center justify-center gap-2"
              >
                Explore Wallpapers
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ══ FEATURED HERO VISUAL ══ */}
      <section className="pb-16 bg-gradient-to-b from-transparent to-white relative z-10 border-b border-slate-100">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-6">
            {MOBILE_WALLPAPERS.map((wp, idx) => (
              <div key={idx} className={`relative rounded-2xl sm:rounded-3xl overflow-hidden shadow-2xl border-4 border-white aspect-[3/4] ${idx % 2 !== 0 ? 'mt-8 sm:mt-12' : ''}`}>
                <Image
                  src={wp.src}
                  alt={wp.alt}
                  fill
                  className="object-cover"
                  sizes="(max-width: 768px) 50vw, 25vw"
                  priority
                />
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ MOBILE WALLPAPERS ══ */}
      <section id="wallpapers" className="py-16 sm:py-24 bg-white border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row sm:items-end justify-between mb-8 sm:mb-12">
            <div className="max-w-2xl text-center sm:text-left mx-auto sm:mx-0">
              <h2 className="text-2xl sm:text-3xl font-black text-[#0f172a] mb-4">15 August Mobile Wallpapers</h2>
              <p className="text-slate-600 text-base sm:text-lg">
                Find patriotic mobile wallpapers designed to bring the spirit of Independence Day to your phone.
              </p>
            </div>
          </div>

          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-6">
            {MOBILE_WALLPAPERS.map((wp, idx) => (
              <div key={idx} className="group relative rounded-2xl overflow-hidden bg-slate-100 border border-slate-200 aspect-[9/16]">
                <Image
                  src={wp.src}
                  alt={wp.alt}
                  fill
                  className="object-cover transition-transform duration-700 group-hover:scale-105"
                  sizes="(max-width: 768px) 50vw, 25vw"
                />
                <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center backdrop-blur-sm">
                  <a href={wp.src} target="_blank" rel="noopener noreferrer" className="px-4 sm:px-5 py-2 sm:py-2.5 bg-white/20 hover:bg-white/30 text-white rounded-full font-bold text-sm sm:text-base backdrop-blur-md transition-all flex items-center gap-2">
                    <ExternalLink className="w-4 h-4" /> <span className="hidden sm:inline">View Wallpaper</span><span className="sm:hidden">View</span>
                  </a>
                </div>
              </div>
            ))}
          </div>
          
          <div className="mt-8 text-center sm:text-left">
            <Link href="#explore" className="inline-flex items-center justify-center sm:justify-start w-full sm:w-auto gap-2 font-bold text-orange-600 hover:text-orange-700">
              Explore More Wallpapers <Check className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* ══ DESKTOP WALLPAPERS ══ */}
      <section className="py-16 sm:py-24 bg-slate-50 border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-8 sm:mb-12">
            <h2 className="text-2xl sm:text-3xl font-black text-[#0f172a] mb-4">Independence Day Desktop Wallpapers</h2>
            <p className="text-slate-600 text-base sm:text-lg">
              Give your desktop a patriotic look with Independence Day wallpapers featuring India's national colors, landmarks and symbols.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-8 max-w-5xl mx-auto">
            {DESKTOP_WALLPAPERS.map((wp, idx) => (
              <div key={idx} className="group relative rounded-2xl overflow-hidden shadow-sm border border-slate-200">
                <Image
                  src={wp.src}
                  alt={wp.alt}
                  width={1200}
                  height={800}
                  className="w-full object-cover transition-transform duration-700 group-hover:scale-105"
                  sizes="(max-width: 768px) 100vw, 50vw"
                />
                <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                  <a href={wp.src} target="_blank" rel="noopener noreferrer" className="px-4 sm:px-5 py-2 sm:py-2.5 bg-white text-slate-900 rounded-full font-bold shadow-lg flex items-center gap-2 hover:scale-105 transition-transform text-sm sm:text-base">
                    <ExternalLink className="w-4 h-4" /> View Wallpaper
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ INDIAN FLAG WALLPAPERS ══ */}
      <section id="explore" className="py-16 sm:py-24 bg-white border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-8 sm:mb-12">
            <h2 className="text-2xl sm:text-3xl font-black text-[#0f172a] mb-4">Indian Flag Wallpapers</h2>
            <p className="text-slate-600 text-base sm:text-lg">
              Celebrate India's national pride with Indian flag and tricolor wallpapers for your phone, desktop and social profiles.
            </p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-6 max-w-5xl mx-auto">
            {FLAG_WALLPAPERS.map((wp, idx) => (
              <div key={idx} className="group relative rounded-2xl overflow-hidden bg-slate-100 border border-slate-200 aspect-[3/4]">
                <Image
                  src={wp.src}
                  alt={wp.alt}
                  fill
                  className="object-cover transition-transform duration-700 group-hover:scale-105"
                  sizes="(max-width: 768px) 50vw, 25vw"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-4">
                  <a href={wp.src} target="_blank" rel="noopener noreferrer" className="text-white font-bold text-xs sm:text-sm flex items-center gap-2 hover:text-orange-400 transition-colors w-fit">
                    <ExternalLink className="w-3 h-3 sm:w-4 sm:h-4" /> View
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ PERSONALIZED POSTER CTA ══ */}
      <section className="py-16 sm:py-20 bg-orange-50 relative overflow-hidden">
        <div className="absolute -top-24 -right-24 w-96 h-96 bg-[#f97316]/10 rounded-full blur-3xl" />
        <div className="absolute -bottom-24 -left-24 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl" />
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <h2 className="text-2xl sm:text-4xl font-black text-[#0f172a] mb-4 sm:mb-6 leading-tight">
            Want a Wallpaper or Poster With Your Own Photo?
          </h2>
          <p className="text-base sm:text-xl text-slate-600 mb-6 sm:mb-8 leading-relaxed max-w-2xl mx-auto">
            Create a personalized Independence Day poster using your own photo. Choose a patriotic style, add your details, complete the payment and let AI generate your personalized HD poster.
          </p>
          
          <Link
            href="/create"
            className="w-full sm:w-auto inline-flex justify-center px-6 sm:px-8 py-3.5 sm:py-4 bg-[#0f172a] text-white rounded-xl sm:rounded-2xl font-black text-base sm:text-lg hover:bg-slate-800 transition-all shadow-lg"
          >
            Create My Personalized Poster
          </Link>
          <p className="mt-4 font-bold text-orange-600 text-sm">Starting at ₹49</p>
        </div>
      </section>

      {/* ══ POSTER STYLE SHOWCASE ══ */}
      <section className="py-16 sm:py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-12 sm:mb-16">
            <h2 className="text-3xl sm:text-4xl font-black text-[#0f172a] mb-4">
              Create Your Own 15 August Poster
            </h2>
            <p className="text-slate-600 text-lg">
              Our AI creates stunning patriotic posters.
            </p>
          </div>

          <div className="mt-8 sm:mt-12 flex overflow-x-auto snap-x snap-mandatory scrollbar-none sm:grid sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 pb-4 px-4 -mx-4 sm:mx-0 sm:px-0 sm:pb-0">
            {AVAILABLE_TEMPLATES.map((tmpl) => (
              <div key={`style-${tmpl.id}`} className="flex-none w-[260px] sm:w-auto bg-slate-50 rounded-2xl sm:rounded-3xl border border-slate-200 overflow-hidden shadow-sm snap-center flex flex-col">
                <div className="relative aspect-[3/4] bg-slate-100 overflow-hidden">
                  <Image
                    src={tmpl.thumbnailImage!}
                    alt={`${tmpl.title} template preview`}
                    fill
                    className="object-cover"
                    sizes="(max-width: 640px) 260px, (max-width: 1024px) 50vw, 33vw"
                    loading="lazy"
                  />
                </div>
                <div className="p-4 sm:p-6 flex-1 flex flex-col text-left">
                  <h3 className="text-lg sm:text-xl font-black text-slate-800 mb-2">{tmpl.title}</h3>
                  <p className="text-xs sm:text-sm text-slate-600 mb-4 sm:mb-6 flex-1">{tmpl.description}</p>
                  
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between mt-auto gap-3 sm:gap-0">
                    <div>
                      <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Price</span>
                      <span className="text-base sm:text-lg font-black text-slate-800">
                        {tmpl.tier === 'premium' && tmpl.id !== 'india-map' && tmpl.id !== 'patriot-creator' ? 'Starting at ₹79' : 
                         tmpl.id === 'india-map' || tmpl.id === 'patriot-creator' ? 'Starting at ₹69' : 'Starting at ₹49'}
                      </span>
                    </div>
                    <Link
                      href="/create"
                      className="w-full sm:w-auto text-center px-4 sm:px-5 py-2.5 bg-[#f97316] text-white font-bold rounded-xl text-sm hover:bg-orange-600 transition-colors shadow-sm"
                    >
                      Create This Poster
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ SOCIAL MEDIA USE CASES ══ */}
      <section className="py-16 sm:py-20 bg-slate-50 border-y border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl font-black text-[#0f172a] mb-4">
            Where Can You Use Independence Day Wallpapers?
          </h2>

          <div className="mt-8 sm:mt-12 grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4 max-w-4xl mx-auto">
            {socialUses.map((use, idx) => (
              <div key={idx} className="bg-white p-4 sm:p-6 rounded-xl sm:rounded-2xl border border-slate-200 shadow-sm flex flex-col items-center gap-2 sm:gap-3">
                <div className="w-10 h-10 sm:w-12 sm:h-12 bg-orange-50 rounded-full flex items-center justify-center text-orange-600">
                  <use.icon className="w-5 h-5 sm:w-6 sm:h-6" />
                </div>
                <span className="font-bold text-slate-800 text-xs sm:text-sm">{use.name}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ RELATED CONTENT ══ */}
      <section className="py-16 sm:py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl font-black text-[#0f172a] mb-8 sm:mb-12">
            More Independence Day Content
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4 max-w-4xl mx-auto">
            <Link href="/15-august-images" className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-6 hover:bg-orange-50 hover:border-orange-200 transition-colors group">
              <h3 className="font-bold text-slate-800 group-hover:text-orange-700 text-sm sm:text-base">15 August 2026 images</h3>
            </Link>
            <Link href="/15-august-poster" className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-6 hover:bg-orange-50 hover:border-orange-200 transition-colors group">
              <h3 className="font-bold text-slate-800 group-hover:text-orange-700 text-sm sm:text-base">15 August posters</h3>
            </Link>
            <Link href="/15-august-status" className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-6 hover:bg-orange-50 hover:border-orange-200 transition-colors group">
              <h3 className="font-bold text-slate-800 group-hover:text-orange-700 text-sm sm:text-base">15 August status</h3>
            </Link>
          </div>
        </div>
      </section>

      {/* ══ SEO CONTENT SECTION ══ */}
      <section className="py-16 bg-slate-50 border-t border-slate-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 prose prose-lg prose-slate">
          <h2 className="text-3xl font-black text-[#0f172a] text-center mb-8">Independence Day 2026 Wallpapers</h2>
          
          <div className="space-y-6 text-slate-600 text-base leading-relaxed">
            <p>
              As India gears up to celebrate its freedom, downloading an <strong>Independence Day 2026 wallpaper</strong> is the perfect way to carry the spirit of the nation with you. Your digital devices—from your smartphone to your laptop—are constant companions, and a beautiful <strong>15 August wallpaper</strong> serves as a proud reminder of our history and progress.
            </p>
            
            <p>
              An <strong>Indian flag wallpaper</strong> is more than just a background image; it is a statement of national pride. Whether you prefer a minimalist tricolor design or a vibrant graphic of India's iconic landmarks, setting an <strong>Independence Day wallpaper</strong> keeps the patriotic spirit alive every time you look at your screen.
            </p>

            <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">Mobile and Desktop Wallpapers</h3>
            
            <p>
              Different devices require different dimensions. Our <strong>15 August 2026 wallpaper</strong> collection respects these formats, providing vertically oriented imagery for mobile lock screens and wider, high-definition backgrounds for desktops and tablets. The clarity and correct aspect ratios ensure that the beauty of the flag is never distorted.
            </p>
            
            <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">Sharing the Patriotism</h3>
            
            <p>
              Beyond personal use, a stunning <strong>15 August wallpaper</strong> is ideal for social media sharing. They make perfect WhatsApp status updates or Instagram stories. However, if you want something truly unique, you can easily transition from standard wallpapers to creating your very own <strong>personalized Independence Day poster</strong> using our intuitive tools. 
            </p>
          </div>
        </div>
      </section>

      {/* ══ WHO IS IT FOR? ══ */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-black text-[#0f172a] mb-12">
            Who Can Use These Independence Day Wallpapers?
          </h2>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-5xl mx-auto">
            {targetAudiences.map((audience, idx) => (
              <div key={idx} className="py-4 px-2 border-b-2 border-slate-100 flex items-center justify-center gap-2">
                <Check className="w-4 h-4 text-emerald-500 shrink-0" />
                <span className="font-bold text-slate-700 text-sm sm:text-base">{audience}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ FAQ SECTION ══ */}
      <section className="py-20 bg-slate-50 border-t border-slate-200">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <HelpCircle className="w-10 h-10 text-orange-400 mx-auto mb-4" />
            <h2 className="text-3xl font-black text-[#0f172a]">
              Frequently Asked Questions
            </h2>
          </div>
          
          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
                <h3 className="text-lg font-bold text-slate-800 mb-2">{faq.q}</h3>
                <p className="text-slate-600 text-sm leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ FINAL CTA ══ */}
      <section className="py-16 sm:py-24 bg-[#0f172a] relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-tr from-orange-900/20 via-transparent to-emerald-900/20 z-0" />
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <h2 className="text-3xl sm:text-5xl font-black text-white mb-4 sm:mb-6 leading-tight">
            Create Your Personalized Independence Day Poster
          </h2>
          <p className="text-lg sm:text-xl text-slate-300 mb-8 sm:mb-10 max-w-2xl mx-auto px-2">
            Turn your Independence Day celebration into something personal. Choose a patriotic design, add your photo and create your own HD 15 August poster.
          </p>
          
          <Link
            href="/create"
            className="w-full sm:w-auto inline-flex justify-center px-6 sm:px-10 py-4 sm:py-5 bg-gradient-to-r from-[#f97316] to-[#ea580c] text-white rounded-xl sm:rounded-2xl font-black text-lg sm:text-xl hover:scale-105 transition-transform shadow-xl shadow-orange-500/20"
          >
            Create My 15 August Poster
          </Link>
          
          <p className="mt-6 text-slate-400 font-medium flex items-center justify-center gap-2 text-sm">
            <Sparkles className="w-4 h-4 text-orange-400" /> Starting at ₹49 • Personalized HD Poster
          </p>
        </div>
      </section>
    </div>
  );
}
