import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { Sparkles, Check, ChevronRight, Image as ImageIcon, Smartphone, Share2, Users, HelpCircle, ArrowRight, Download, ExternalLink } from "lucide-react";
import IndianFlag from "@/components/IndianFlag";
import { TEMPLATES } from "@/data/templates";

// Filter only available templates
const AVAILABLE_TEMPLATES = TEMPLATES.filter((t) => t.isAvailable);

export const metadata: Metadata = {
  title: "15 August 2026 Images | HD Independence Day Images",
  description: "Explore HD 15 August 2026 Independence Day images, patriotic photos and poster designs. Download patriotic images or create a personalized Independence Day poster with your own photo.",
  alternates: { canonical: "https://freedom2026.in/15-august-images" },
  openGraph: {
    title: "15 August 2026 Images | HD Independence Day Images",
    description: "Explore HD 15 August 2026 Independence Day images, patriotic photos and poster designs. Download patriotic images or create a personalized Independence Day poster with your own photo.",
    url: "https://freedom2026.in/15-august-images",
    type: "website",
    images: [
      {
        url: "https://freedom2026.in/images/hero_poster_main.png",
        width: 1080,
        height: 1350,
        alt: "15 August 2026 Independence Day Image",
      },
    ],
  },
};

const GALLERY_IMAGES = [
  {
    src: "/images/hero_poster_main.png",
    alt: "15 August 2026 Independence Day main image design",
    category: "Independence Day",
  },
  {
    src: "/images/classic-india-style.png",
    alt: "15 August 2026 Independence Day Indian flag image",
    category: "Indian Flag",
  },
  {
    src: "/images/modern-india-style.png",
    alt: "Happy Independence Day 2026 patriotic image",
    category: "Patriotic",
  },
  {
    src: "/images/india-map-style.png",
    alt: "15 August India map Independence Day image",
    category: "India",
  },
  {
    src: "/images/hero_poster_left.png",
    alt: "Happy 15 August 2026 Independence Day creative image",
    category: "15 August",
  },
  {
    src: "/images/hero_poster_right.png",
    alt: "Freedom India 2026 poster image",
    category: "Freedom",
  },
  {
    src: "/images/Public-Leader-Style.png",
    alt: "Indian National Pride 15 August 2026 image",
    category: "National Pride",
  },
  {
    src: "/images/bengali-style.png",
    alt: "15 August regional patriotic image",
    category: "15 August",
  },
  {
    src: "/images/hindi-style.png",
    alt: "15 August Hindi Independence Day images",
    category: "Patriotic",
  }
];

export default function August15ImagesPage() {
  const faqs = [
    {
      q: "What are 15 August 2026 images?",
      a: "They are patriotic digital photos, graphics, and poster designs celebrating India's 80th Independence Day on August 15, 2026."
    },
    {
      q: "Where can I use 15 August images?",
      a: "You can use them across all major social media platforms, including WhatsApp, Facebook, Instagram, and for personal sharing with friends and family."
    },
    {
      q: "Can I use these images for WhatsApp status?",
      a: "Yes. Our collection includes vertical images that fit perfectly as WhatsApp status updates without losing quality."
    },
    {
      q: "Can I use 15 August images on Instagram?",
      a: "Yes, the images are high-definition and can be shared on Instagram as posts or stories."
    },
    {
      q: "Can I create a personalized Independence Day image?",
      a: "Yes. We offer an AI-powered tool where you can upload your photo, add your name and city, and generate a customized 15 August poster."
    },
    {
      q: "How can I create a poster with my own photo?",
      a: "Simply browse to our poster creation tool, choose your favorite template, upload a clear photo, enter your details, and securely pay to generate the personalized image."
    },
    {
      q: "How much does a personalized poster cost?",
      a: "Personalized posters start at ₹49. Premium templates may have different prices, which will be clearly displayed before you begin the process."
    },
    {
      q: "Can I download my personalized HD poster?",
      a: "Yes. After the payment is complete and your poster is generated by our AI, you will be able to download the HD image directly to your device."
    }
  ];

  const socialUses = [
    { name: "WhatsApp Status", icon: Smartphone },
    { name: "Facebook Posts", icon: Share2 },
    { name: "Instagram Stories", icon: ImageIcon },
    { name: "Instagram Posts", icon: ImageIcon },
    { name: "Profile Pictures", icon: Users },
    { name: "WhatsApp DP", icon: Users },
    { name: "Personal Messages", icon: Smartphone },
    { name: "Community Posts", icon: Users }
  ];

  const targetAudiences = [
    "Students",
    "Families",
    "Teachers",
    "Businesses",
    "Creators",
    "Community Groups",
    "Schools",
    "Social Media Users"
  ];

  // Schema generation
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": faqs.map(faq => ({
      "@type": "Question",
      "name": faq.q,
      "acceptedAnswer": {
        "@type": "Answer",
        "text": faq.a
      }
    }))
  };

  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    "itemListElement": [
      {
        "@type": "ListItem",
        "position": 1,
        "name": "Home",
        "item": "https://freedom2026.in/"
      },
      {
        "@type": "ListItem",
        "position": 2,
        "name": "15 August 2026 Images",
        "item": "https://freedom2026.in/15-august-images"
      }
    ]
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />

      {/* ══ HEADER / HERO SECTION ══ */}
      <section className="relative pt-24 pb-16 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-orange-50 via-white to-emerald-50 z-0" />
        <div className="absolute inset-0 bg-[url('/patterns/topography.svg')] opacity-5 z-0" />
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="text-center max-w-4xl mx-auto space-y-4 sm:space-y-6">
            <div className="inline-flex items-center gap-1.5 sm:gap-2 bg-white border border-slate-200 text-slate-700 text-[10px] sm:text-xs font-bold px-3 sm:px-4 py-1 sm:py-1.5 rounded-full shadow-sm">
              <IndianFlag className="w-3.5 h-2.5 sm:w-4 sm:h-3" />
              <span>Independence Day Collection</span>
            </div>
            
            <h1 className="text-3xl sm:text-5xl md:text-6xl font-black text-[#0f172a] tracking-tight leading-tight px-2">
              15 August 2026 Images
            </h1>
            
            <h2 className="text-lg sm:text-2xl font-bold text-slate-700 px-4">
              HD Independence Day Images for India
            </h2>
            
            <p className="text-sm sm:text-lg text-slate-600 max-w-2xl mx-auto leading-relaxed px-2">
              Explore a collection of patriotic 15 August 2026 images celebrating India's Independence Day. Find HD visuals for social media posts, WhatsApp status, profile pictures, stories and personal sharing.
            </p>
            
            <div className="pt-2 sm:pt-4 flex flex-col sm:flex-row items-center justify-center gap-3 sm:gap-4 px-4">
              <Link
                href="/create"
                className="w-full sm:w-auto px-6 sm:px-8 py-3.5 sm:py-4 bg-gradient-to-r from-[#f97316] to-[#ea580c] text-white rounded-xl sm:rounded-2xl font-black text-base sm:text-lg shadow-lg shadow-orange-500/25 hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2"
              >
                <Sparkles className="w-4 h-4 sm:w-5 sm:h-5" />
                Create Your Personalized Poster
              </Link>
              <Link
                href="#gallery"
                className="w-full sm:w-auto px-6 sm:px-8 py-3.5 sm:py-4 bg-white text-slate-700 rounded-xl sm:rounded-2xl font-bold text-base sm:text-lg border-2 border-slate-200 hover:border-slate-300 hover:bg-slate-50 transition-all flex items-center justify-center gap-2"
              >
                Explore Images
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* ══ FEATURED IMAGE GALLERY ══ */}
      <section id="gallery" className="py-16 bg-white border-y border-slate-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-black text-[#0f172a]">
              15 August 2026 Images
            </h2>
          </div>

          <div className="columns-2 md:columns-3 lg:columns-4 gap-4 space-y-4">
            {GALLERY_IMAGES.map((img, idx) => (
              <div key={idx} className="break-inside-avoid relative group rounded-2xl overflow-hidden bg-slate-100 border border-slate-200">
                <Image
                  src={img.src}
                  alt={img.alt}
                  width={500}
                  height={700}
                  className="w-full object-cover transition-transform duration-500 group-hover:scale-105"
                  sizes="(max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
                  loading={idx < 4 ? "eager" : "lazy"}
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex flex-col justify-end p-4">
                  <div className="flex items-center justify-between">
                    <span className="bg-white/20 backdrop-blur-md text-white text-[10px] font-bold px-2 py-1 rounded-md uppercase tracking-wider">
                      {img.category}
                    </span>
                    <a
                      href={img.src}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="w-8 h-8 bg-white/20 backdrop-blur-md rounded-full flex items-center justify-center hover:bg-white/40 transition-colors"
                      title="Open Image"
                    >
                      <ExternalLink className="w-4 h-4 text-white" />
                    </a>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ FREE IMAGE SECTION ══ */}
      <section className="py-12 bg-slate-50 border-b border-slate-100">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h2 className="text-2xl font-bold text-slate-800 mb-4">
            Free Independence Day Images
          </h2>
          <p className="text-slate-600 text-base sm:text-lg">
            Explore patriotic Independence Day images for your social posts, status updates and personal sharing. Feel free to open and view the high-quality assets available above to celebrate 15 August.
          </p>
        </div>
      </section>

      {/* ══ PERSONALIZED POSTER CTA ══ */}
      <section className="py-16 sm:py-20 bg-orange-50 relative overflow-hidden">
        <div className="absolute -top-24 -right-24 w-96 h-96 bg-[#f97316]/10 rounded-full blur-3xl" />
        <div className="absolute -bottom-24 -left-24 w-96 h-96 bg-emerald-500/10 rounded-full blur-3xl" />
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <h2 className="text-2xl sm:text-4xl font-black text-[#0f172a] mb-4 sm:mb-6 leading-tight">
            Want an Independence Day Image With Your Own Photo?
          </h2>
          <p className="text-base sm:text-xl text-slate-600 mb-6 sm:mb-8 leading-relaxed max-w-2xl mx-auto">
            Turn your own photo into a personalized 15 August 2026 poster. Choose a patriotic style, upload your photo, add your details and let AI create a personalized HD poster for you.
          </p>
          
          <Link
            href="/create"
            className="w-full sm:w-auto inline-flex justify-center px-6 sm:px-8 py-3.5 sm:py-4 bg-[#0f172a] text-white rounded-xl sm:rounded-2xl font-black text-base sm:text-lg hover:bg-slate-800 transition-all shadow-lg"
          >
            Create My 15 August Poster
          </Link>
          <p className="mt-4 font-bold text-orange-600 text-sm">Starting at ₹49</p>
        </div>
      </section>

      {/* ══ POSTER STYLE SHOWCASE ══ */}
      <section className="py-16 sm:py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-3xl mx-auto mb-12 sm:mb-16">
            <h2 className="text-3xl sm:text-4xl font-black text-[#0f172a] mb-4">
              Create Your Personalized Independence Day Poster
            </h2>
            <p className="text-slate-600 text-lg">
              Explore our collection of custom templates and styles.
            </p>
          </div>

          <div className="mt-8 sm:mt-12 flex overflow-x-auto snap-x snap-mandatory scrollbar-none sm:grid sm:grid-cols-2 lg:grid-cols-3 gap-4 sm:gap-6 pb-4 px-4 -mx-4 sm:mx-0 sm:px-0 sm:pb-0">
            {AVAILABLE_TEMPLATES.map((tmpl) => (
              <div key={`style-${tmpl.id}`} className="flex-none w-[260px] sm:w-auto bg-slate-50 rounded-2xl sm:rounded-3xl border border-slate-200 overflow-hidden shadow-sm snap-center flex flex-col">
                <div className="relative aspect-[3/4] bg-slate-100 overflow-hidden">
                  <Image
                    src={tmpl.thumbnailImage!}
                    alt={`${tmpl.title} template preview`}
                    fill
                    className="object-cover"
                    sizes="(max-width: 640px) 260px, (max-width: 1024px) 50vw, 33vw"
                    loading="lazy"
                  />
                </div>
                <div className="p-4 sm:p-6 flex-1 flex flex-col text-left">
                  <h3 className="text-lg sm:text-xl font-black text-slate-800 mb-2">{tmpl.title}</h3>
                  <p className="text-xs sm:text-sm text-slate-600 mb-4 sm:mb-6 flex-1">{tmpl.description}</p>
                  
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between mt-auto gap-3 sm:gap-0">
                    <div>
                      <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider block">Price</span>
                      <span className="text-base sm:text-lg font-black text-slate-800">
                        {tmpl.tier === 'premium' && tmpl.id !== 'india-map' && tmpl.id !== 'patriot-creator' ? 'Starting at ₹79' : 
                         tmpl.id === 'india-map' || tmpl.id === 'patriot-creator' ? 'Starting at ₹69' : 'Starting at ₹49'}
                      </span>
                    </div>
                    <Link
                      href="/create"
                      className="w-full sm:w-auto text-center px-4 sm:px-5 py-2.5 bg-[#f97316] text-white font-bold rounded-xl text-sm hover:bg-orange-600 transition-colors shadow-sm"
                    >
                      Create This Poster
                    </Link>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ SOCIAL MEDIA USE CASES ══ */}
      <section className="py-16 sm:py-20 bg-slate-50 border-y border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl font-black text-[#0f172a] mb-4">
            Use These 15 August Images On
          </h2>
          <p className="text-slate-600 text-sm sm:text-lg max-w-2xl mx-auto mb-8 sm:mb-12 px-2">
            Celebrate Independence Day across the platforms where you connect with friends, family and your community.
          </p>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4 max-w-4xl mx-auto">
            {socialUses.map((use, idx) => (
              <div key={idx} className="bg-white p-4 sm:p-6 rounded-xl sm:rounded-2xl border border-slate-200 shadow-sm flex flex-col items-center gap-2 sm:gap-3">
                <div className="w-10 h-10 sm:w-12 sm:h-12 bg-orange-50 rounded-full flex items-center justify-center text-orange-600">
                  <use.icon className="w-5 h-5 sm:w-6 sm:h-6" />
                </div>
                <span className="font-bold text-slate-800 text-xs sm:text-sm">{use.name}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ IMAGE CATEGORIES ══ */}
      <section className="py-16 sm:py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-2xl sm:text-3xl font-black text-[#0f172a] mb-8 sm:mb-12">
            Explore Independence Day Image Categories
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4 max-w-5xl mx-auto">
            <Link href="/15-august-poster" className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-6 hover:bg-orange-50 hover:border-orange-200 transition-colors group">
              <h3 className="font-bold text-slate-800 group-hover:text-orange-700 text-sm sm:text-base">15 August Posters</h3>
            </Link>
            <Link href="/15-august-status" className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-6 hover:bg-orange-50 hover:border-orange-200 transition-colors group">
              <h3 className="font-bold text-slate-800 group-hover:text-orange-700 text-sm sm:text-base">15 August Status</h3>
            </Link>
            <Link href="/independence-day-images" className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-6 hover:bg-orange-50 hover:border-orange-200 transition-colors group">
              <h3 className="font-bold text-slate-800 group-hover:text-orange-700 text-sm sm:text-base">Independence Day Images</h3>
            </Link>
            <Link href="/create" className="bg-slate-50 border border-slate-200 rounded-xl p-4 sm:p-6 hover:bg-orange-50 hover:border-orange-200 transition-colors group">
              <h3 className="font-bold text-slate-800 group-hover:text-orange-700 text-sm sm:text-base">Create Personalized Image</h3>
            </Link>
          </div>
        </div>
      </section>

      {/* ══ SEO CONTENT SECTION ══ */}
      <section className="py-16 bg-slate-50 border-t border-slate-100">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 prose prose-lg prose-slate">
          <h2 className="text-3xl font-black text-[#0f172a] text-center mb-8">15 August 2026 Images for Independence Day</h2>
          
          <div className="space-y-6 text-slate-600 text-base leading-relaxed">
            <p>
              The 15th of August marks a significant milestone in India's history. As we celebrate Independence Day in 2026, millions of Indians proudly share <strong>15 August 2026 images</strong> to express their love for the nation. Sharing these visuals has become an essential part of modern digital celebrations.
            </p>
            
            <p>
              High-quality <strong>Independence Day images 2026</strong> help convey deep emotions of patriotism, freedom, and national pride. Whether you are searching for a beautiful <strong>15 August photo</strong> featuring the Indian flag or looking for creative graphics to post on your timeline, having access to vibrant, meaningful imagery makes your celebration more impactful.
            </p>

            <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">Why People Share 15 August Images</h3>
            
            <p>
              Sharing a patriotic <strong>15 August poster</strong> or image is a simple yet powerful way to connect with your community. From school students to business owners, everyone uses these images to show their respect for the freedom fighters who made our independence possible. A striking <strong>15 August image</strong> captures the essence of this historic day.
            </p>
            
            <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">Social Media and WhatsApp Status</h3>
            
            <p>
              On Independence Day, social media platforms are flooded with saffron, white, and green. Updating your WhatsApp status with <strong>15 August images</strong> is the easiest way to wish all your contacts at once. High-definition (HD) Indian flag imagery and patriotic posts look beautiful on mobile screens, making them perfect for Instagram stories and Facebook updates.
            </p>
            
            <h3 className="text-xl font-bold text-slate-800 mt-8 mb-4">Personalized Independence Day Posters</h3>
            
            <p>
              While standard <strong>15 August images</strong> are wonderful, creating a personalized poster takes your celebration to the next level. Instead of sharing generic graphics, you can generate an HD poster that includes your own photo, name, and city. This personalized touch makes your <strong>15 August 2026 celebrations</strong> unique and helps you stand out in the digital crowd. Browse our styles, choose your favorite, and create a custom 15 August photo that represents your personal patriotism.
            </p>
          </div>
        </div>
      </section>

      {/* ══ WHO IS IT FOR? ══ */}
      <section className="py-20 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-black text-[#0f172a] mb-12">
            Who Are These Independence Day Images For?
          </h2>
          
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 max-w-5xl mx-auto">
            {targetAudiences.map((audience, idx) => (
              <div key={idx} className="py-4 px-2 border-b-2 border-slate-100 flex items-center justify-center gap-2">
                <Check className="w-4 h-4 text-emerald-500 shrink-0" />
                <span className="font-bold text-slate-700 text-sm sm:text-base">{audience}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ FAQ SECTION ══ */}
      <section className="py-20 bg-slate-50 border-t border-slate-200">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <HelpCircle className="w-10 h-10 text-orange-400 mx-auto mb-4" />
            <h2 className="text-3xl font-black text-[#0f172a]">
              Frequently Asked Questions
            </h2>
          </div>
          
          <div className="space-y-4">
            {faqs.map((faq, idx) => (
              <div key={idx} className="bg-white border border-slate-200 rounded-2xl p-6 shadow-sm">
                <h3 className="text-lg font-bold text-slate-800 mb-2">{faq.q}</h3>
                <p className="text-slate-600 text-sm leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ══ FINAL CTA ══ */}
      <section className="py-16 sm:py-24 bg-[#0f172a] relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-tr from-orange-900/20 via-transparent to-emerald-900/20 z-0" />
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <h2 className="text-3xl sm:text-5xl font-black text-white mb-4 sm:mb-6 leading-tight">
            Create Your Own 15 August 2026 Poster
          </h2>
          <p className="text-lg sm:text-xl text-slate-300 mb-8 sm:mb-10 max-w-2xl mx-auto px-2">
            Don't just share an Independence Day image—create one with your own photo. Choose your favorite patriotic style and create a personalized HD poster for Independence Day.
          </p>
          
          <Link
            href="/create"
            className="w-full sm:w-auto inline-flex justify-center px-6 sm:px-10 py-4 sm:py-5 bg-gradient-to-r from-[#f97316] to-[#ea580c] text-white rounded-xl sm:rounded-2xl font-black text-lg sm:text-xl hover:scale-105 transition-transform shadow-xl shadow-orange-500/20"
          >
            Create My Personalized Poster
          </Link>
          
          <p className="mt-6 text-slate-400 font-medium flex items-center justify-center gap-2 text-sm">
            <Sparkles className="w-4 h-4 text-orange-400" /> Starting at ₹49 • Personalized HD Poster
          </p>
        </div>
      </section>
    </div>
  );
}
